---
- hosts: hypervisor
  become: true
  tasks:

    # Check if virtualization is enabled
    - name: Read CPU Attributes
      shell: lscpu | grep Virtualization
      register: reg_check_virt

    - name: Fail if CPU does not support Virtualization
      fail:
        msg: "CPU does not support Virtualization"
      when:
        - "'Virtualization' not in reg_check_virt.stdout"

    # Install KVM-QEMU
    - name: Install KVM-QEMU
      yum:
        name: ['qemu-kvm', 'libvirt', 'virt-install', 'libguestfs-tools', 'python3-libguestfs']
        state: present

    # Enable and start libvirtd
    - name: Enable libvirtd
      systemd:
        name: libvirtd
        enabled: true
        state: started
