---
- hosts: hypervisor
  tasks:  

    - name: Provision KVM
      include_role:
        name: infra_server_kvm_cloud_create
      vars:
        cloud_image_loc: /lab/img
        vm_root_dir: /lab/kvm
        vm_keys_dir: /lab/keys
        vm_xml_dir: /lab/xml
